FROM golang:1.22 AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker

FROM alpine:3.19

WORKDIR /app

COPY --from=build /app/worker .

EXPOSE 8081

CMD ["./worker"]
